import { ThemeProviderEmailMe } from "../components/theme-provider";
import "./globals.css";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html className="h-full">
			<body className={`h-full`}>
				<ThemeProviderEmailMe attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
					<div className="text-dark dark:text-white">{children}</div>
				</ThemeProviderEmailMe>
			</body>
		</html>
	);
}
